Loop the test

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -59,7 +59,19 @@ jobs:
             # Mock for pcap slice opening to avoid hanging Actions Runner.
             # See https://github.com/brimdata/zui/pull/2987
             echo "application/vnd.tcpdump.pcap; /usr/bin/true" >> /home/runner/.mailcap
-            /usr/bin/xvfb-run --auto-servernum -s "-screen 0 1280x1024x24" ${{ inputs.run-target }}
+            num=1
+            success=0
+            fail=0
+            while [ $num -le 100 ]; do
+              { /usr/bin/xvfb-run --auto-servernum -s "-screen 0 1280x1024x24" ${{ inputs.run-target }}; err="$?"; } || true
+              if [ $err -eq 0 ]; then
+                success=$(expr $success + 1)
+              else
+                fail=$(expr $fail + 1)
+              fi
+              num=$(expr $num + 1)
+              echo "success=$success fail=$fail"
+            done
           else
             ${{ inputs.run-target }}
           fi
